# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/**/Dto/'
            - '../src/**/Migrations/'
            - '../src/**/ValueObject/'
            - '../src/**/Command/'
            - '../src/**/Query/'
            - '../src/**/Event/'

    App\NotificationPublisher\Application\Notifier\NotifierService:
        arguments:
            $channel: '%env(NOTIFICATION_CHANNEL)%'

    App\NotificationPublisher\Application\RetryManager\RetryManager:
        arguments:
            $retryInterval: '%env(RETRY_INTERVAL)%'

    App\NotificationPublisher\Application\Throttling\ThrottlingService:
        arguments:
            $throttlingLimit: '%env(THROTTLING_LIMIT)%'
            $throttlingInterval: '%env(THROTTLING_INTERVAL)%'

    App\SharedKernel\Application\EventBus\EventBusInterface:
        public: true

    App\SharedKernel\Infrastructure\EventBus\EventBus:
        public: true
